// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddBio struct {
	Name string `json:"name"`
	Age  int    `json:"Age"`
}

type BioData struct {
	Name string `json:"name"`
	Age  int    `json:"Age"`
}
